### ISSUE TITLE
Not able to register modules or compile DAG on VS Code version 1.78.2 for mac

### ISSUE THREAD

**Issue by akundaliya** [zilto/vscode-hamilton#5]
Hi,

I am not able to see any button to register or de-register modules after I updated VS code to version 1.78.2. Also from command as well when I try to register a module and compile the dag, nothing happens.

**Comment by zilto** [comment]
Hi @akundaliya! 

I take note of your issue.

The extension is in a very early state. This week, I should be releasing an update that includes an extension walkthrough within VSCode itself and a logging channel to improve issue tracking.
